### ISSUE TITLE
where I can set the scale of Kwin_wayland

### ISSUE THREAD

**Issue by ffs-akl** [stefonarch/LXQt-Wayland-files#10]
I tried Lxqt-kwin(wayland session) ,  if I setted the scale=1.5 in $HOME/.config/kwinoutputconfig.json, After logging back in, the scale=1.5 automatically becomes scale=1 in the $HOME/.config/kwinoutputconfig.json. and kwin_wayland worked with scale=1
I had no other choice but to install kscreen and systemsettings to set it up through the GUI and kwin_wayland worked with scale=1.5 .
After setting it up through the GUI, I deleted the kscreen and systemsettings wiht the command:"sudo pacman -Rsn kscreen systemsettings",     then  changed scale=1.5 to 1 directly in the  $HOME/.config/kwinoutputconfig.json.  but  After logging back in again,   the scale=1 automatically becomes scale=1.5 in the $HOME/.config/kwinoutputconfig.json.  and kwin_wayland worked with scale=1.5.
So, I think the scale of kwin_wayland should be setted in somewhere else.  
Could you help look at this and tell me where I should set it up manually?

**Comment by stefonarch** [comment]
Those are the downsides of using kwin_wayland IMO, no idea how it does that. You could check for recently changed config files in your home dir.
There is also a scaling setting in `lxqt-config-session`, afaik we should rely only on that.

**Comment by ffs-akl** [comment]
> There is also a scaling setting in `lxqt-config-session`, afaik we should rely only on that.

It is useful except for chrome,chromium and  the Server-side decoration of all applications 
the scale by kwin_wayland can act globally.

**Comment by ffs-akl** [comment]
>Those are the downsides of using kwin_wayland IMO, no idea how it does that. You could check for recently changed config files in your home dir.

I have checked, nothing be changed except  the scale in $HOME/.config/kwinoutputconfig.json.

PLASMA is so complex that many programs will behave differently when run in PALSMA versus outside of PALSMA

**Comment by stefonarch** [comment]
> > There is also a scaling setting in `lxqt-config-session`, afaik we should rely only on that.
> 
> It is useful except for chrome,chromium and the Server-side decoration of all applications the scale by kwin_wayland can act globally.

True, I see also thunderbird and firefox not scaled, but I don't need scaling so never looked really into it. SSD can be changed in theme. `kwin_wayland` has also a `--scale` option, never tested.
xwayland apps like chromium (default if not configured for wayland) and element aren't scaled too.

**Comment by ffs-akl** [comment]
Thank you!  --scale is a possible option, but it's better to install kscreen with systemsettings.

**Comment by ffs-akl** [comment]
--scale does not work, if don't want to install kscreen+systemsettings,  use the kscreen-doctor command provided by libkscreen to set it. kscreen+systemsettings do it with this command as well.
