### ISSUE TITLE
Build failure with PKGBUILD for lxqt-panel with taskbar

### ISSUE THREAD

**Issue by jjramsey** [stefonarch/LXQt-Wayland-files#11]
The error messages I get when running `makepkg -sic` are as follows:
```
[ 71%] Building CXX object plugin-taskbar/CMakeFiles/taskbar.dir/lxqttaskbutton.cpp.o
/home/jjramsey/AUR/lxqt-panel-git-w-taskbar/src/lxqt-panel/plugin-taskbar/lxqttaskbutton.cpp: In member function ‘virtual void LXQtTaskButton::contextMenuEvent(QContextMenuEvent*)’:
/home/jjramsey/AUR/lxqt-panel-git-w-taskbar/src/lxqt-panel/plugin-taskbar/lxqttaskbutton.cpp:693:87: error: ‘SetLayer’ is not a member of ‘LXQtTaskBarBackendAction’
  693 |     layerMenu->setEnabled(mBackend->supportsAction(mWindow, LXQtTaskBarBackendAction::SetLayer));
      |                                                                                       ^~~~~~~~
/home/jjramsey/AUR/lxqt-panel-git-w-taskbar/src/lxqt-panel/plugin-taskbar/lxqttaskbutton.cpp:697:28: error: redeclaration of ‘LXQtTaskBarWindowLayer currentLayer’
  697 |     LXQtTaskBarWindowLayer currentLayer = mBackend->getWindowLayer(mWindow);
      |                            ^~~~~~~~~~~~
/home/jjramsey/AUR/lxqt-panel-git-w-taskbar/src/lxqt-panel/plugin-taskbar/lxqttaskbutton.cpp:695:28: note: ‘LXQtTaskBarWindowLayer currentLayer’ previously declared here
  695 |     LXQtTaskBarWindowLayer currentLayer = mBackend->getWindowLayer(mWindow);
      |                            ^~~~~~~~~~~~
make[2]: *** [plugin-taskbar/CMakeFiles/taskbar.dir/build.make:311: plugin-taskbar/CMakeFiles/taskbar.dir/lxqttaskbutton.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1972: plugin-taskbar/CMakeFiles/taskbar.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

Not sure whether the problem is with the git branch, an errant dependency in the PKGBUILD, or what.

**Comment by stefonarch** [comment]
It's exactly this error here: https://github.com/lxqt/lxqt-panel/pull/2046#issuecomment-2199765739

You could try this patch in the meantime, because we are about to change the plugin logic and it won't be fixed in this PR probably.

**Comment by jjramsey** [comment]
I managed to apply the patch, but then ended up with the same `ld` error in the comment that you just mentioned: "/usr/bin/ld: cannot find -llxqt-panel-backend-wlroots: No such file or directory"

**Comment by stefonarch** [comment]
Oh, I see.
 If it's really due to the recent  rebase you could compile the previous commit: `git checkout 1fc55941df0a55bf52e1f82b0a4864a6e8fe333b` , which has also better support for kwin_wayland.

**Comment by jjramsey** [comment]
I just tried out that previous commit you mentioned. Basically, in the PKGBUILD file, I replaced
```
source=("git+https://github.com/LXQt-Marcus-Fork/lxqt-panel#branch=wlroots-taskbar")
```
with
```
source=("git+https://github.com/LXQt-Marcus-Fork/lxqt-panel#commit=1fc55941df0a55bf52e1f82b0a4864a6e8fe333b")
```
While it *compiles*, the resulting lxqt-panel's taskbar doesn't work on Labwc, Hyprland, or Sway. I don't know if that's a bug in the taskbar, or if that particular commit just doesn't have to do with the `wlroots-taskbar` branch.

ETA: The taskbar *does* work on kwin_wayland, just as you said it would.

**Comment by stefonarch** [comment]
Got the same result here (didn't check kwin though), and my branch has the same issue as in the PR. Looks there is no way to compile it atm until the refactoring is started. I'll attach my working package.
[lxqt-panel.zip](https://github.com/user-attachments/files/16118264/lxqt-panel.zip)

**Comment by jjramsey** [comment]
Is that a working package with the panel for a wlroots-taskbar?

**Comment by stefonarch** [comment]
Yes, at least it works here on arch. It was compiled before the rebase. Atm only the taskbar for kwin can be compiled (what you did indirectly).

**Comment by stefonarch** [comment]
A working branch is used now for the PKBBUILD: https://github.com/stefonarch/lxqt-panel/tree/wayland_panel. Version is `pkgver=0.16.1.r434.g0017a2f5`.

The desktop switch plugin is not working atm, not even under kwin_wayland as supposed.
