### ISSUE TITLE
Question about QTerminal under kwin_wayland

### ISSUE THREAD

**Issue by tsujan** [stefonarch/LXQt-Wayland-files#2]
You've written, "QTerminal crashes when try to split (only on kwin_wayland)". We had a similar issue a year ago (I fixed it). Would you please attach a backtrace (after `where`)?

**Comment by stefonarch** [comment]
I'll test it (and other stuff) under a regular plasma session first.

**Comment by stefonarch** [comment]
https://github.com/lxqt/qterminal/issues/1031

**Comment by tsujan** [comment]
Thanks!
