### ISSUE TITLE
use of waybox instead of labwc

### ISSUE THREAD

**Issue by daktras420** [stefonarch/LXQt-Wayland-files#3]
i wrote the author of labwc about how qt based apps behave in their project and why its an issue the author was very condescending so for now i am switching to kwinft or kwin. and planning to work on using waybox instead i am noticing waybox has a lot of focus on kde and qt integration and can even use the kde-panel and thought maybe we could make more headway then using labwc any help ideas or thoughts are appreciated also how or where does the kwin_wayland.rule need to be placed on my system to be used?

**Comment by stefonarch** [comment]
IMO you should read a bit more and write less.
The panel doesn't load if you use the default configuration on any wayland configuration and it's not implementing any of the wayland protocols yet.

>where does the ` kwin_wayland.rule `
You can import the window rules in `systemsetting5` > window management > window rules

I'll lock into waybox, it can be added but won't replace labwc which is working real fine with `waybar` and `yatbfw` and it's not their fault that lxqt-panel|runner|notification haven't yet implemented wayland code.

**Comment by daktras420** [comment]
Thank you for looking at waybox. While the author of labwc doesn't
understand that without modifications like what your working on lxqt
components and models at this time do not run on wayland and i get wayland
protocols aren't being used as of yet in lxqt. But was looking for
workarounds and asking questions to better understand i wont big you again!

**Comment by stefonarch** [comment]
I launched it in the same way as the other compositors, for some reason lxqt-panel was already at the top, together  with a plasmashell panel which had it's settings go out of screen and has the same issues as lxqt-panel (it's a normal window).

I found no way to configure keyboard (us) and touchpad (slow), no config file, which makes it unusable for me. Maybe plasmashell should be killed, but then still you need a config file for basic stuff like keyboard layout.

**Comment by daktras420** [comment]
I understand the dev only uses irc to answer questions... Once i switch my
desktop to plasma for now i was planning on asking questions concerning how
to change configuration and such.
