### ISSUE TITLE
the configuration of SDDM (wayland) using labwc as the compositor

### ISSUE THREAD

**Issue by ffs-akl** [stefonarch/LXQt-Wayland-files#7]
Good day!
I encountered a issue about sddm(wayland) using labwc as compositor.    and have tried all sorts of things but none of them worked.
Would you tell me how to configure it?
There should be a lot of people who have encountered this issue.

**Comment by stefonarch** [comment]
You mean probably in `sddm.conf`
```
   [Wayland] section:

       CompositorCommand=
              Path of the compositor to execute when  starting  the  greeter.   Default
              value is "weston --shell=kiosk".
```
I had never understood how this should work. Weston isn't installed and if it is I never saw it active  with `DisplayServer=wayland`, I experimented too with labwc and nothing worked, like` labwc -C /tmp`, following https://wiki.archlinux.org/title/SDDM#KDE_Plasma_/_KWin

**Comment by ffs-akl** [comment]
It seems that I can only refer to the sway distribution of fedora, they use sway to start SDDM, and I think labwc should be similar

**Comment by stefonarch** [comment]
Do you have a link to the config files?

**Comment by stefonarch** [comment]
I retested with 
```
[General]
...
DisplayServer=wayland
GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell

[Wayland]
...
CompositorCommand=labwc -C /tmp

 ```
 and I got a black labwc window with just reconfigure|exit on right click. Then I found out that's my theme which isn't compatible. With no theme or

```
[Theme]
Current=breeze
```

it's working fine. I checked the presence of the labwc process in tty.

Edit: it looks like `GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell` isn't needed and even not mentioned in the manpage and was the reason for the failure with my theme.

**Comment by stefonarch** [comment]
Config files go to  `/var/lib/sddm/.config/labwc/` I found out [here](https://bbs.archlinux.org/viewtopic.php?id=289612). Finally a faster cursor movement which was awfully slow on sddm.

**Comment by ffs-akl** [comment]
thank you,  it is work

**Comment by ffs-akl** [comment]
I've run into another issue, I've made an issue in SDDM, but it doesn't seem to be responded, is there any good way to solve it
https://github.com/sddm/sddm/issues/1945

**Comment by ffs-akl** [comment]
It's not a issue with labwc or sddm, it's a issue with the maya theme, after changed a qt6 based theme, sddm
+labwc works fine, even not needed to set LIBGL_ALWAYS_SOFTWARE=1
