### ISSUE TITLE
In lxqt-labwc,show desktop widget didn't work , Is this normal?

### ISSUE THREAD

**Issue by ffs-akl** [stefonarch/LXQt-Wayland-files#8]
show desktop is work fine in lxqt-kwin.  not in lxqt-labwc.  
The icon is also incorrect in lxqt-labwc.

**Comment by stefonarch** [comment]
→ https://github.com/stefonarch/LXQt-Wayland-files/blob/main/lxqt-panel.md#show-desktop-button
