### ISSUE TITLE
There are two different icons of pcmanfm-qt in fast launcher and taskbar

### ISSUE THREAD

**Issue by ffs-akl** [stefonarch/LXQt-Wayland-files#9]
I set the theme to  breeze ,  the icon of pcmanfm-qt in the panel is the Original icon， in the fast lanucher  it is breeze style icon.
Can I change the icon in Fast Lanuncher or Taskbar?

**Comment by stefonarch** [comment]
It has it's own icon, but in the menu it's the default theme icon. 
You could copy `/usr/share/applications/pcmanfm-qt.desktop` to `~/.local/share/applications/`, edit it and use this in the quicklaunch. Icon name should be `pcmanfm-qt`.

**Comment by ffs-akl** [comment]
thank you,This worked.
 but only can chang the icon in lanuner and menu,  Even if I specify  a specific path and icon file name in the dektop file, it won't change the icon in the taskbar,  it always is the Original icon（The ugly yellow icon）

**Comment by stefonarch** [comment]
You can substitute /usr/share/icons/hicolor/scalable/apps/pcmanfm-qt.svg with one of your choice.

**Comment by ffs-akl** [comment]
Thank you,  the issue is solved.  There will be no problems until the next updated revsion.  maybe lxqt-panel  will fixed this issue in next revsion

**Comment by ffs-akl** [comment]
in lxqt-kwin,  the icon of pcmanfm-qt is normal，It seems that these QT programs are a bit more kwin-friendly

**Comment by stefonarch** [comment]
Solved be https://github.com/lxqt/pcmanfm-qt/commit/a291ad08988e728e059603852445729cebdf70bf

**Comment by ffs-akl** [comment]
good to know,  So, if user set theme to breeze,    The icons of pcmanfm-qt everywhere in LXQT is the blue one in the Breeze style? 
But I feel like it's going to be a yellow icon everywhere.   Because I've tried to build pcmanf.desktop under /us/share/applications/     and changed the item of icon  from system-file-manager to pcmanfm-qt.  result is a yellow icon eveywhere

Edited
it is incongruous that  a yellow icon appears in the theme with blue as the main color

**Comment by stefonarch** [comment]
Yes, it will be the same icon everywhere.  You can replace `/usr/share/icons/Papirus/48x48/apps/system-file-manager.svg` by `ls /usr/share/icons/breeze/apps/48/system-file-manager.svg`.

> it is incongruous that a yellow icon appears in the theme with blue as the main color

Also firefox icon isn't blue in blue themes. Every app which has an own icon won't change it if the selected theme doesn't provide one.

**Comment by ffs-akl** [comment]
Sounds reasonable，beauty and ugliness can't be objectively defined.  anyway, thank you for the selfless help
 just my personal opinion, maybe it's time to redesign pcmanfm-qt's icon. would you think firefox's icons are easier to coordinate with the theme than pcmanfm-qtr's ?
